# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true
    #http_method_override: true

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        # On laisse symfony gérer les sessions
        handler_id: 'session.handler.native_file'
        # On spécifie qu'on va stocker les données de la session dans var/sessions
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
        # On définit la durée de vie de la sseion qui est à 1 heure ici
        cookie_lifetime: 3600
        cookie_secure: auto
        cookie_samesite: lax
        enabled: true

    #esi: true
    #fragments: true
    php_errors:
        log: true
